"""
Prompts package for the GenAI SMS Chatbot.

This package contains prompts used by various agents in the system.
"""

from .main_agent_prompts import (
    MAIN_SYSTEM_PROMPT,
    CANDIDATE_NAME_EXTRACTION_PROMPT,
    CANDIDATE_PHONE_NUMBER_EXTRACTION_PROMPT,
    DYNAMIC_WELCOME_MESSAGE_PROMPT,
    WELCOME_AND_REGISTRATION_PROMPT,
    DYNAMIC_JOB_INTEREST_PROMPT,
    POST_SCHEDULING_MESSAGE_PROMPT,
    REGISTRATION_PROMPT
)
from .scheduler_advisor_prompts import (
    SCHEDULER_SYSTEM_PROMPT
)
from .info_advisor_prompts import (
    INFO_ADVISOR_SYSTEM_PROMPT,
    AI_RESPONSE_PROMPT_TEMPLATE,
    INTENT_ANALYSIS_PROMPT
)

__all__ = [
    'MAIN_SYSTEM_PROMPT',
    'CANDIDATE_NAME_EXTRACTION_PROMPT',
    'CANDIDATE_PHONE_NUMBER_EXTRACTION_PROMPT',
    'DYNAMIC_WELCOME_MESSAGE_PROMPT',
    'WELCOME_AND_REGISTRATION_PROMPT',
    'REGISTRATION_PROMPT',
    'DYNAMIC_JOB_INTEREST_PROMPT',
    'POST_SCHEDULING_MESSAGE_PROMPT',
    'SCHEDULER_SYSTEM_PROMPT',
    'INFO_ADVISOR_SYSTEM_PROMPT',
    'AI_RESPONSE_PROMPT_TEMPLATE',
    'INTENT_ANALYSIS_PROMPT'
] 