version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sms_chatbot_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sms_chatbot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: tech_sqlserver
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./data/db_Tech.sql:/docker-entrypoint-initdb.d/db_Tech.sql

volumes:
  mongodb_data:
  sqlserver_data:
