"""
Responses package for the GenAI SMS Chatbot.

This package contains predefined response constants used by various agents in the system.
"""

from .main_agent_fallback_responses import (
    MAIN_AGENT_WELCOME_BACK_RESPONSE,
    MAIN_AGENT_WELCOME_BACK_NO_HISTORY_RESPONSE,
    MAIN_AGENT_NEW_USER_REGISTRATION_RESPONSE,
    MAIN_AGENT_WELCOME_INITIAL_RESPONSE,
    MAIN_AGENT_JOB_INTEREST_CONFIRMATION_RESPONSE,
    MAIN_AGENT_REGISTRATION_FALLBACK_RESPONSE,
    MAIN_AGENT_ERROR_RESPONSE,
    MAIN_AGENT_NO_PREVIOUS_CONVERSATION
)

from .info_advisor_fallback_responses import (
    INFO_ADVISOR_GENERAL_FALLBACK_RESPONSE,
    INFO_ADVISOR_REQUIREMENTS_RESPONSE_TEMPLATE,
    INFO_ADVISOR_BENEFITS_RESPONSE_TEMPLATE,
    INFO_ADVISOR_COMPANY_INFO_RESPONSE_TEMPLATE,
    INFO_ADVISOR_SALARY_RESPONSE_TEMPLATE,
    INFO_ADVISOR_GREETING_RESPONSE_TEMPLATE,
    INFO_ADVISOR_POSITION_AVAILABLE_SINGLE_TEMPLATE,
    INFO_ADVISOR_POSITION_AVAILABLE_MULTIPLE_TEMPLATE,
    INFO_ADVISOR_POSITION_DEFAULT_TEMPLATE,
    INFO_ADVISOR_POSITION_UNAVAILABLE_SINGLE_TEMPLATE,
    INFO_ADVISOR_POSITION_UNAVAILABLE_SINGLE_DEFAULT_TEMPLATE,
    INFO_ADVISOR_POSITION_UNAVAILABLE_MULTIPLE_TEMPLATE,
    INFO_ADVISOR_POSITION_UNAVAILABLE_MULTIPLE_DEFAULT_TEMPLATE
)


__all__ = [
    'MAIN_AGENT_WELCOME_BACK_RESPONSE',
    'MAIN_AGENT_WELCOME_BACK_NO_HISTORY_RESPONSE',
    'MAIN_AGENT_NEW_USER_REGISTRATION_RESPONSE',
    'MAIN_AGENT_WELCOME_INITIAL_RESPONSE',
    'MAIN_AGENT_JOB_INTEREST_CONFIRMATION_RESPONSE',
    'MAIN_AGENT_REGISTRATION_FALLBACK_RESPONSE',
    'MAIN_AGENT_ERROR_RESPONSE',
    'MAIN_AGENT_NO_PREVIOUS_CONVERSATION',
    'INFO_ADVISOR_GENERAL_FALLBACK_RESPONSE',
    'INFO_ADVISOR_REQUIREMENTS_RESPONSE_TEMPLATE',
    'INFO_ADVISOR_BENEFITS_RESPONSE_TEMPLATE',
    'INFO_ADVISOR_COMPANY_INFO_RESPONSE_TEMPLATE',
    'INFO_ADVISOR_SALARY_RESPONSE_TEMPLATE',
    'INFO_ADVISOR_GREETING_RESPONSE_TEMPLATE',
    'INFO_ADVISOR_POSITION_AVAILABLE_SINGLE_TEMPLATE',
    'INFO_ADVISOR_POSITION_AVAILABLE_MULTIPLE_TEMPLATE',
    'INFO_ADVISOR_POSITION_DEFAULT_TEMPLATE',
    'INFO_ADVISOR_POSITION_UNAVAILABLE_SINGLE_TEMPLATE',
    'INFO_ADVISOR_POSITION_UNAVAILABLE_SINGLE_DEFAULT_TEMPLATE',
    'INFO_ADVISOR_POSITION_UNAVAILABLE_MULTIPLE_TEMPLATE',
    'INFO_ADVISOR_POSITION_UNAVAILABLE_MULTIPLE_DEFAULT_TEMPLATE',
] 